version: 2
jobs:

  build-4.08:
    docker:
      - image: ocaml/opam:ubuntu-lts-ocaml-4.08
    steps:
      - checkout
      - run:
          name: Build
          command: ./bin/ci

workflows:
  version: 2
  build:
    jobs:
      - build-4.08
