version: 2.1

orbs:
  ocaml: oni-tech/ocaml-build@dev:tim-5 # use latest version
  github: haskell-works/github-release@1.3.3

workflows:
  build:
    jobs:
      - ocaml/build-with-cci-cache:
          name: OCaml 4.04
          executor: ocaml/ocaml-4_04
